config/routes.rb
Rails.application.routes.draw do

  resources :perfiles, only: [:show, :update]
  resources :blogs
  get 'comentarios/create'
  get 'comentarios/destroy'

  root :to => "home#index"
  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }, path: "usuario", path_names: { sign_in: 'login', sign_out: 'logout', password: 'secreto', confirmation: 'verificacion', unlock: 'bloquedo', registration: 'registro', sign_up: 'dejame_entrar' }
  
  resources :users, path: 'usuario' do
    member do
        post :follow
      end
    resources :portafolios, except: [:index], path_names: { new: "crear", edit: "editar" } do
      collection do
            post 'sort'
      end
      resources :adjuntos, only: [:destroy]
      resources :comentarios, only: [:create, :destroy]
    end
  end
  mount Bootsy::Engine => '/bootsy', as: 'bootsy'
end

app/models/portafolio.rb
class Portafolio < ActiveRecord::Base
  belongs_to :user
  has_many :comentarios, dependent: :destroy
  has_many :adjuntos, dependent: :destroy
  accepts_nested_attributes_for :adjuntos
  acts_as_liker
  acts_as_likeable
  is_impressionable
  validates :titulo, presence: true
  extend FriendlyId
  friendly_id :titulo, use: [:slugged, :finders]
end

app/controllers/portafolios_controller.rb
class PortafoliosController < ApplicationController
  before_action :set_portafolio, only: [:edit, :update]
  impressionist :actions=>[:show,:index]


  def follow
    @user = User.find(params[:id])
     # => This assumes you have a variable current_user who is authenticated
    if current_user.toggle_follow!(@user)
      redirect_to user_path, :notice => "Lo Sigues"
    else
      redirect_to user_path, :alert => "Ya no lo Sigues"
    end
  end

  def index
    if current_user.pago
      @portafolios = Portafolio.all
    else
       redirect_to root_path, :alert => "Para poder ver los portafolios de otros tienes que estar estar al día con tus cuotas"
    end
  end


  def show
    @portafolios = Portafolio.find(params[:id])
    @user = current_user
    @imagenes = @portafolios.adjuntos.order('position')
    @seguidores = @user.followers(User)
    @siguiendo = @user.followees(User)
    @comentarios = @portafolios.comentarios.all
    impressionist(@portafolios)
  end


  def new
    if current_user.pago
      @user = current_user
      @portafolio = current_user.portafolios.new
      @imagenes = @portafolio.adjuntos.build
    else
       redirect_to root_path, :alert => "Para poder crear portafolios tienes que pagar la colegiatura"
    end
  end


  def edit
    @user = current_user
    # @portafolio = @user.portafolios.find_by(id: params[:id])
    @imagenes = @portafolio.adjuntos.build
    @portafolios = Portafolio.find(params[:id])
    @imagen = @portafolios.adjuntos.all
  end


  def create
    if current_user.pago
      # render text: params and return
      @portafolio = current_user.portafolios.new(portafolio_params)

      respond_to do |format|
        if @portafolio.save
          params[:adjuntos]['imagen'].each do |a|
            @user = current_user
            @imagenes = @portafolio.adjuntos.create!(:imagen => a, :portafolio_id => @portafolio.id, :user_id => @user.id)
          end
          format.html { redirect_to user_portafolio_path(current_user, @portafolio), notice: 'Portafolio was successfully created.' }
          format.json { render :show, status: :created, location: @portafolio }
        else
          format.html { redirect_to :back }
          format.json { render json: @portafolio.errors, status: :unprocessable_entity }
        end
      end
    else
       redirect_to root_path, :alert => "Para poder crear portafolios tienes que pagar la colegiatura"
    end
  end


def update
    respond_to do |format|
      if @portafolio.update(portafolio_params)
        unless params[:adjuntos].nil?
         params[:adjuntos]['imagen'].each do |a|
           @user = current_user
           @imagenes = @portafolio.adjuntos.create!(:imagen => a, :portafolio_id => @portafolio.id, :user_id => @user.id)
          end
        end
        format.html { redirect_to user_portafolio_path(current_user, @portafolio), notice: 'Portafolio was successfully updated.' }
        format.json { render :show, status: :ok, location: @portafolio }
      else
        format.html { render :edit }
        format.json { render json: @portafolio.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @portafolio = Portafolio.find(params[:id])
    if current_user.id === @portafolio.user_id
      @portafolio = current_user.portafolios.find(params[:id]).destroy
      respond_to do |format|
        format.html { redirect_to user_path(current_user), notice: 'Portafolio was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      redirect_to user_path(current_user), alert: 'No puedes eliminar otros protafolios'
    end
  end

  def sort
    params[:imagen].each_with_index do |id, index|
        imagen = Adjunto.find(id)
        imagen.update_attribute(:position, index) if imagen
    end
    render nothing: true
  end


  private

    def set_portafolio
        if current_user.id === Portafolio.find(params[:id]).user_id
          @portafolio = current_user.portafolios.find(params[:id])
          @comentarios = @portafolio.comentarios.all
        else
          redirect_to user_path(current_user), alert: 'No tienes permiso para editar'
        end
    end

    def portafolio_params
      params.require(:portafolio).permit(:titulo, :descripcion, :user_id, adjuntos_attributes: [:id, :portafolio_id, :user_id, :imagen, :position])
    end
end

app/helpers/portafolios_helper.rb
module PortafoliosHelper
end

app/views/portafolios/_editar.html.erb
<%= simple_form_for ([@user, @portafolio]), :html => {:multipart => true} do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :titulo %>
    <%= f.input :descripcion %>
    <% if @imagen.empty? %>
		<%= f.fields_for :adjuntos do |p| %>
		    <div class="field">
		 		<%= p.label :imagen %><br>
		    	<%= p.file_field :imagen, :multiple => true, name: "adjuntos[imagen][]" %>
		   </div>
		<% end %>
	<% else %>
    	<div class="field">
	 		<%= f.label :imagen %><br>
	    	<%= f.file_field :imagen, :multiple => true, name: "adjuntos[imagen][]" %>
	   </div>
    <% end %>
	<% @imagen.each do |p| %>
	    <li id="imagen_<%= p.id %>">
	      <%= image_tag p.imagen_url %>
	      <% if user_signed_in? %>
	        <%= link_to "Eliminar", user_portafolio_adjunto_path(current_user.slug, params[:id],p), {method: :delete} %>
	      <% end %>
	    </li>
	<% end %>
  </div>
  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/portafolios/_form.html.erb
<%= simple_form_for ([@user, @portafolio]), :html => {:multipart => true} do |f| %>

<% if f.error_notification %>
   <div class="alert alert-error fade in">
     <a class="close" data-dismiss="alert" href="#">&times;</a>
     <%= f.error_notification %>
   </div>
<% end %>

  <div class="form-inputs">
    <%= f.input :titulo %>
    <%= f.input :descripcion %>
	<%= f.fields_for :adjuntos do |p| %>
	    <div class="field">
	 		<%= p.label :imagen %><br>
	    	<%= p.file_field :imagen, :multiple => true, name: "adjuntos[imagen][]" %>
	   </div>
	<% end %>
  </div>
  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/portafolios/edit.html.erb
<h1>Editing portafolio</h1>

<%= render 'editar' %>
<%= link_to 'Show', user_portafolio_path(@portafolio.user, @portafolio.slug) %>

app/views/portafolios/index.html.erb
<h1>Listing portafolios</h1>

<table>
  <thead>
    <tr>
      <th>Titulo</th>
      <th>Descripcion</th>
      <th>Creado</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @portafolios.each do |portafolio| %>
      <tr>
        <td><%= portafolio.titulo %></td>
        <td><%= portafolio.descripcion %></td>
        <td><%= portafolio.created_at %></td>
        <td><%= link_to 'Show', user_portafolio_path(portafolio.user, portafolio.slug) %></td>
        <td><%= link_to 'Edit', edit_user_portafolio_path(portafolio.user, portafolio.slug) %></td>
        <td><%= #link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

<% if current_user === @portafolios %>
  <%= link_to 'New Portafolio', new_user_portafolio_path %>
<% end %>

app/views/portafolios/new.html.erb
<h1>New portafolio</h1>


<%= render 'form' %>

<%= link_to 'Back', user_portafolios_path %>

app/views/portafolios/show.html.erb
<div>
<p id="notice"><%= notice %></p>
<div class="large-4 columns"> 
	<img src="http://placehold.it/500x500&amp;text=Logo">

    <div class="hide-for-small panel">
      <h3><%= @user.name if @user.name %></h3>
      <h5 class="subheader"><%= @user.email if @user.email %></h5>
      <hr>
		<% @seguidores.each do |s| %>
		<h5>Personas que me siguen</h5>
		<ul>
			<li class="<%= s.id %>"><%=link_to s.name, controller: "users", action: "show", id: s.slug %></li>
		</ul>
		<% end %>

		<h5>Mis amigos</h5>
		<ul>
			<% @siguiendo.each do |s| %>
				<li class="<%= s.id %>"><%=link_to s.name, controller: "users", action: "show", id: s.slug %></li>
			<% end %>
		</ul>
		<div class="cantidad-visitas">
			<%= @portafolios.impressionist_count(:filter=>:session_hash) %>
		</div>	

    </div>
    <% if user_signed_in? %>
		<% unless current_user === @user  %>
		    <div class="panel callout radius">
			      <h6>
					<% if current_user.follows?(@user)  %>
						<%= link_to("Dejar de Seguir", follow_user_path(@user), method: :post, class: "seguir") %>
					<% else %>
						<%= link_to("Seguir", follow_user_path(@user), method: :post, class: "seguir") %>
					<% end %>
			      </h6>
		    </div>

		<% end %>
	<% end %>
</div>
<div class="large-8 columns">
	
	  <div>
		<h1>
		  <%= @portafolios.titulo %>
		</h1>
	  </div>
	  <div>
	  	<ul <% if current_user.id === @portafolios.user_id %>id="sortable"  data-update-url="<%= sort_user_portafolios_url %>"<% end %>>
		  <% @imagenes.each do |p| %>
		    <li id="imagen_<%= p.id %>">
		     <%= image_tag p.imagen_url %>
		      <% if current_user.id === @portafolios.user_id %>
		        <%= link_to "Eliminar", user_portafolio_adjunto_path(current_user.slug, params[:id],p), {method: :delete} %>
		      <% end %>
		    </li>
		  <% end %>
		</ul>
		<div class="comentario panel">
			<p>
		  		<%= @portafolios.descripcion %>
			</p>
		</div>
	  </div>
		<% if current_user.id === @portafolios.user_id %>
			<%= link_to 'Show', user_portafolio_path(@portafolios.user, @portafolios.slug) %>
			<%= link_to 'Edit', edit_user_portafolio_path(@portafolios.user, @portafolios.slug) %>
		<% end %>

	<!-- desplegar comentarios -->
	<div >
	<h5>haz un comentarios</h5>
	<% if user_signed_in? %>
	   <%= simple_form_for ([@user, @portafolios, current_user.comentarios.new ]) do |f|%>
	    <%= f.input :comentario, as: :text  %> 
	    <%= f.submit 'Comentar', :class => 'button right' %>
	   <% end %>
	<% else %>
	<p>Tienes que Registrarte</p>
	<% end %>
	</div>
	<div class="clearfix"></div>
		
	<% #unless @comentarios.nil? %>
		<div class="panel">
			<% @comentarios.each do |c| %>
			   <strong>
			   	<%= c.user.name %>
			   </strong>
			 <p>
			   <%= c.comentario %>
			 </p> 
			<% end %>
		</div>
	<% #end %>
</div>
</div>