config/routes.rb
Rails.application.routes.draw do

  resources :perfiles, only: [:show, :update]
  resources :blogs
  get 'comentarios/create'
  get 'comentarios/destroy'

  root :to => "home#index"
  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }, path: "usuario", path_names: { sign_in: 'login', sign_out: 'logout', password: 'secreto', confirmation: 'verificacion', unlock: 'bloquedo', registration: 'registro', sign_up: 'dejame_entrar' }
  
  resources :users, path: 'usuario' do
    member do
        post :follow
      end
    resources :portafolios, except: [:index], path_names: { new: "crear", edit: "editar" } do
      collection do
            post 'sort'
      end
      resources :adjuntos, only: [:destroy]
      resources :comentarios, only: [:create, :destroy]
    end
  end
  mount Bootsy::Engine => '/bootsy', as: 'bootsy'
end

app/models/blog.rb
class Blog < ActiveRecord::Base
	belongs_to :user
	include Bootsy::Container
	validates :titulo, presence: true
	validates :cuerpo, presence: true
	extend FriendlyId
  	friendly_id :titulo, use: [:slugged, :finders]
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_filter :authenticate_user!, except: [:show]
  before_action :set_blog, only: [ :update, :destroy]

  def index
    @blogs = Blog.all
  end

  def show
    @blog = Blog.find(params[:id])
  end

  def new
    if current_user.admin?
      @blog = current_user.blogs.new
    else
      redirect_to root_url, notice: 'No tienes permiso para eso'
    end
  end

  def edit
    if current_user.admin?
     @blog = current_user.blogs.find(params[:id])
   else
      redirect_to root_url, notice: 'No tienes permiso para eso'
    end
  end

  def create
    @blog = current_user.blogs.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    if current_user.admin?
      @blog.destroy
      respond_to do |format|
        format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      redirect_to root_url, notice: 'No tienes permiso para eso'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = current_user.blogs.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:titulo, :cuerpo, :user_id, :bootsy_image_gallery_id)
    end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_form.html.erb
<%= simple_form_for(@blog) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :titulo %>
    <%= f.input :cuerpo, as: :bootsy, editor_options: {html: true} %>
  </div>
  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing blog</h1>

<%= render 'form' %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<h1>Listing blogs</h1>

<table>
  <thead>
    <tr>
      <th>Titulo</th>
      <th>Cuerpo</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blogs.each do |blog| %>
      <tr>
        <td><%= blog.titulo %></td>
        <td><%= blog.cuerpo %></td>
        <td><%= blog.user_id %></td>
        <td><%= link_to 'Show', blog %></td>
        <td><%= link_to 'Edit', edit_blog_path(blog) %></td>
        <td><%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blog', new_blog_path %>

app/views/blogs/new.html.erb
<h1>New blog</h1>

<%= render 'form' %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Titulo:</strong>
  <%= @blog.titulo %>
</p>

<p>
  <strong>Cuerpo:</strong>
  <%= @blog.cuerpo.html_safe %>
</p>

<p>
  <strong>User:</strong>
  <%= @blog.user_id %>
</p>

<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %>