config/routes.rb
Rails.application.routes.draw do

  resources :perfiles, only: [:show, :update]
  resources :blogs
  get 'comentarios/create'
  get 'comentarios/destroy'

  root :to => "home#index"
  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }, path: "usuario", path_names: { sign_in: 'login', sign_out: 'logout', password: 'secreto', confirmation: 'verificacion', unlock: 'bloquedo', registration: 'registro', sign_up: 'dejame_entrar' }
  
  resources :users, path: 'usuario' do
    member do
        post :follow
      end
    resources :portafolios, except: [:index], path_names: { new: "crear", edit: "editar" } do
      collection do
            post 'sort'
      end
      resources :adjuntos, only: [:destroy]
      resources :comentarios, only: [:create, :destroy]
    end
  end
  mount Bootsy::Engine => '/bootsy', as: 'bootsy'
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :omniauthable,
         :recoverable, :rememberable, :trackable, :validatable
  enum role: [:user, :vip, :admin]
  after_initialize :set_default_role, :if => :new_record?
  def set_default_role
    self.role ||= :user
    self.pago ||= false
  end
  # asociaciones
  has_many :comentarios, :through => :portafolios, dependent: :destroy
  has_many :blogs, dependent: :destroy
  has_one :perfil, dependent: :destroy
  has_many :portafolios, dependent: :destroy
  # Validaciones
  validates :name, presence: true
  validates :name, uniqueness: true
  validates :name, length: {
     minimum: 3,
     maximum: 20,
     too_short: "debe tener minimo %{count} letras",
     too_long: "nombre de usuario demaciado largo, max %{count} letras"
   }
  validates :name, format: { with: /\A[0-9a-zA-Z]+\z/,
     message: "solo numeros y letras" }

  validates :fechapago, presence: { if: 'pago.present?', message: "necesitas introducir fecha de pago" }
  
  # Omniauth 
  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.nickname
    end
  end
  

  def self.new_with_session(params,session)
    if session["devise.user_attributes"]
      new(session["devise.user_attributes"],without_protection: true) do |user|
        user.attributes = params
        user.valid?
      end
    else
      super
    end
  end

  def password_required?
    super && provider.blank?
  end

  def update_with_password(params, *options)
    if encrypted_password.blank?
      update_attributes(params, *options)
    else
      super
    end
  end
 # Gemas 
  acts_as_follower
  acts_as_followable

  extend FriendlyId
  friendly_id :name, use: [:slugged, :finders]
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  after_action :verify_authorized, except: [:show, :follow]


  def follow
    @user = User.find(params[:id])
     # => This assumes you have a variable current_user who is authenticated
    if current_user.toggle_follow!(@user)
      redirect_to user_path, :notice => "Lo Sigues"
    else
      redirect_to user_path, :alert => "Ya no lo Sigues"
    end
  end

  def index
    @search = User.search(params[:q])
    @users = @search.result(distinct: true)
    authorize @users
  end

  def show
    @user = User.find(params[:id])
    @seguidores = @user.followers(User)
    @siguiendo = @user.followees(User)
    @portafolios = @user.portafolios.all
    unless current_user.id == @user.id
      case current_user.pago && @user.pago
      when true
      when @user.pago? 
        unless current_user.admin?
          redirect_to root_path, :alert => "El usuario #{@user.name} no tiene permiso para que vean su portafolios"
        end
      end
    end
  end

  def update
    @user = User.find(params[:id])
    authorize @user
    if @user.update_attributes(secure_params)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "No puedes actualizar el usuario, recuerde que debe introduccir fecha de pago, cuando este activado el checkbox"
    end
  end

  def destroy
    user = User.find(params[:id])
    authorize user
    unless user == current_user
      user.destroy
      redirect_to users_path, :notice => "Usuario eliminado."
    else
      redirect_to users_path, :notice => "No puedes eliminarte a ti mismo."
    end
  end

  private

  def secure_params
    params.require(:user).permit(:role, :pago, :fechapago, :avatar)
  end

end

app/views/users/_user.html.erb
<%= form_for(user) do |f| %>
	<td><%= link_to user.name, user %></td>	
	<td><%= user.email %></td>	
    <td><%= f.select(:role, User.roles.keys.map {|role| [role.titleize,role]}) %></td>	
    <td class="checkbox_<%= user.id %>"><%= f.check_box(:pago) %></td>	
    <td class="fecha_<%= user.id %>">
    	<%= f.date_field(:fechapago) %>
    </td>	
    <td><%= f.submit 'Actualizar', :class => 'button-xs' %></td>	
<% end %>
<td><%= link_to("Eliminar Usuario", user_path(user), :data => { :confirm => "Administrador estas seguro?" }, :method => :delete, :class => 'button-xs') unless user == current_user %></td>	

app/views/users/index.html.erb
<div class="container">
  <div class="row">
  <h3>Buscar Usuarios</h3>
<div class="margintop-20px">
<%= search_form_for @search do |f| %>
<div class="small-8 medium-8 columns">
    <%= f.search_field :name_cont, :placeholder => "Busqueda de Usuarios" %>
  	<%= f.check_box :pago_true %>
    <%= f.label :pago_true, "Pagos al día"%>
</div>
  <div class="small-4 medium-4 columns">
  	<%= f.submit "Buscar",  :class =>'postfix small button expand' %>
  </div>
<% end %>

  
</div>
<div class="clearfix"></div>
    <h3>Usuarios</h3>
    <div>
<table>
  <thead>
    <tr>
      <th><%= sort_link @search, :name, "Nombre de Usuario" %></th>
      <th><%= sort_link @search, :email, "E-Mail de Usuario" %></th>
      <th><%= sort_link @search, :role, "Nivel de Usuario" %></th>
      <th><%= sort_link @search, :pago, "Estan al día con los pagos?" %></th>
      <th><%= sort_link @search, :fechapago, "Fecha de pago" %></th>
    </tr>
  </thead>
  <tbody>

	 <% @users.each do |user| %>
		<tr>
			<%= render user %>
		</tr>            
	<% end %>
  </tbody>
</table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div>
  <div class="large-4 small-12 columns"> <img src="http://placehold.it/500x500&amp;text=Logo">
    <div class="hide-for-small panel">
      <h3><%= @user.name if @user.name %></h3>
      <h5 class="subheader"><%= @user.email if @user.email %></h5>
      <hr>
      <% @seguidores.each do |s| %>
      <h5>Personas que me siguen</h5>
      <ul>
        <li class="<%= s.id %>"><%=link_to s.name, controller: "users", action: "show", id: s.slug %></li>
      </ul>
      <% end %>
      <h5>Mis amigos</h5>
      <ul>
        <% @siguiendo.each do |s| %>
        <li class="<%= s.id %>"><%=link_to s.name, controller: "users", action: "show", id: s.slug %></li>
        <% end %>
      </ul>
    </div>
    <% if user_signed_in? %>
    <% unless current_user === @user  %>
    <a href="#">
    <div class="panel callout radius">
      <h6>
        <% if current_user.follows?(@user)  %>
        <%= link_to("Dejar de Seguir", follow_user_path(@user), method: :post, class: "seguir") %>
        <% else %>
        <%= link_to("Seguir", follow_user_path(@user), method: :post, class: "seguir") %>
        <% end %>
      </h6>
    </div>
    </a>
    <% end %>
    <% end %>
  </div>
  <div class="large-8 columns">
    <div class="row">
      <div class="large-12 columns">
        <div class="panel">
          <div class="row">
            <% unless @user.pago? %>
            <div class="large-10 small-6 columns"> <strong>Te Recordamos que:</strong>
              <hr>
              <b> Para poder empezar a subir portafolios, puedes hacer tu pago <a href="#">acá</a> </b> </div>
            <% end %>
            <% if @portafolios.empty? && @user.pago? && current_user.id == @user.id %>
            <div> <strong>Empieza a subir tus Proyectos</strong>
              <hr>
              <div class="columns"> <%= link_to 'Crear un Portafolio', new_user_portafolio_path(current_user.slug), class: "button expand" %> </div>
            </div>
            <% end %>
            <div class="row">
              <% @portafolios.each do |s| %>
              <div class="large-4 small-6 columns"> <img src="http://placehold.it/1000x1000&amp;text=Thumbnail">
                <div class="panel">
                  <h5><%= link_to s.titulo, user_portafolio_path(s.user.slug, s.slug)  %></h5>
                  <% if current_user === @user %>
                  <ul>
                    <li> <%= link_to 'Edit', edit_user_portafolio_path(s.user, s.slug) %> </li>
                    <li> <%= link_to 'Eliminar', user_portafolio_path(s.user, s.slug), {method: :delete} %> </li>
                  </ul>
                  <% end %>
                </div>
              </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>