config/routes.rb
Rails.application.routes.draw do

  resources :perfiles, only: [:show, :update]
  resources :blogs
  get 'comentarios/create'
  get 'comentarios/destroy'

  root :to => "home#index"
  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }, path: "usuario", path_names: { sign_in: 'login', sign_out: 'logout', password: 'secreto', confirmation: 'verificacion', unlock: 'bloquedo', registration: 'registro', sign_up: 'dejame_entrar' }
  
  resources :users, path: 'usuario' do
    member do
        post :follow
      end
    resources :portafolios, except: [:index], path_names: { new: "crear", edit: "editar" } do
      collection do
            post 'sort'
      end
      resources :adjuntos, only: [:destroy]
      resources :comentarios, only: [:create, :destroy]
    end
  end
  mount Bootsy::Engine => '/bootsy', as: 'bootsy'
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Zurb Foundation %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div data-alert class="alert-box round <%= name.to_s == 'notice' ? 'success' : 'alert' %>">
      <%= content_tag :div, msg %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Zurb Foundation 5 %>
<nav class="top-bar" data-topbar>
  <div class="row">
	  <ul class="title-area">
	    <li class="name"><%= link_to 'Home', root_path %></li>
	    <li class="toggle-topbar menu-icon"><a href="#">Menu</a></li>
	  </ul>
	  <div class="top-bar-section">
	    <ul>
	      <%= render 'layouts/navigation_links' %>
	    </ul>
	  </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
  <li><%= link_to 'Editar Cuenta', edit_user_registration_path %></li>
  <li><%= link_to 'Salir', destroy_user_session_path, :method=>'delete' %></li>
  <li><%= link_to 'Editar Perfil', perfil_path(current_user) %></li>
  <li><%= link_to 'Mi Portafolio', user_path(current_user) %></li>
<% else %>
  <li><%= link_to 'Entrar', new_user_session_path %></li>
  <li><%= link_to 'Registrase', new_user_registration_path %></li>
  <li><%= link_to "Entrar con Twitter", user_omniauth_authorize_path(:twitter) %></li> 
<% end %>
<% if user_signed_in? %>
  <% if current_user.admin? %>
    <li><%= link_to 'Usuarios', users_path %></li>
  <% end %>
  <% if current_user.admin? %>
    <li><%= link_to 'Crear Blog', new_blog_path %></li>
  <% end %>
  <% if current_user.pago? %>
    <li><%= link_to 'Crear un Portafolio', new_user_portafolio_path(current_user.slug) %></li>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Disenadores Chile" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Disenadores Chile" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%# Modernizr is required for Zurb Foundation %>
    <%= javascript_include_tag 'vendor/modernizr' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>


      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
    <div class="row">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </div>
    </main>
  </body>
</html>